### ISSUE TITLE
volume directories seem to be wrong?

### ISSUE THREAD

**Issue by xternaal** [pfelk/docker#10]
Hi,
When building the docker-compose the docker seems to point to /usr/share/logstash/etc... when infact the pipelines etc just point to /etc/... 
also the maxmind points to /usr/share/logstash/GeoIP and not /usr/share/GeoIP

If I change it to /usr/share/GeoIP it then works. However I am still having issues with the first volume issue above and am reluctant to make wholesale changes through the config files as obviously im doing something wrong if it works for everyone else :) ? 

Cheers

**Comment by a3ilson** [comment]
@xternaal - update/fixed a number of issues.  Tested and working...please confirm and close this issue.

**Comment by xternaal** [comment]
All working - Many Thanks!
