### ISSUE TITLE
logstash can not connect to localhost_9200

### ISSUE THREAD

**Issue by hcwwadmin** [pfelk/docker#14]
logstash     | [WARN ] 2020-10-21 21:04:11.839 [Ruby-0-Thread-12: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.6.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:241] elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}

**Comment by a3ilson** [comment]
@hcwwadmin - I apologize for the inconvenience.  I failed to properly update the `50-outputs.conf` file.  The host should have been `http://elastic:9200` and not `http://localhost:9200`

Additionally, I found that both the `35-ruels-desc.conf` and `36-ports-desc.conf` files resulted in logstash crashing.

Please give it another try with the revised files.  I've tested without issue.

**Comment by hcwwadmin** [comment]
the error is gone
thanks for your help

**Comment by kk0201** [comment]
Running into same issue as this.

logstash    | [INFO ] 2022-01-27 21:19:12.147 [[pfelk]-pipeline-manager] elasticsearch - New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
logstash    | [INFO ] 2022-01-27 21:19:12.157 [[pfelk]-pipeline-manager] elasticsearch - Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
logstash    | [WARN ] 2022-01-27 21:19:12.168 [[pfelk]-pipeline-manager] elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1] failed: Connection refused (Connection refused)"}
logstash    | [WARN ] 2022-01-27 21:19:12.974 [[pfelk]-pipeline-manager] grok - Relying on default value of `pipeline.ecs_compatibility`, which may change in a future major release of Logstash. To avoid unexpected changes when upgrading Logstash, please explicitly declare your desired ECS Compatibility mode.


logstash    | [WARN ] 2022-01-27 21:31:53.556 [Ruby-0-Thread-19: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.2.3-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:215] elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error {:url=>"http://localhost:9200/", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :message=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connect to localhost:9200 [localhost/127.0.0.1] failed: Connection refused (Connection refused)"}

**Comment by a3ilson** [comment]
@kk0201 - thanks! The issue was just fixed...had a typo where http://localhost:9200 should have been http://es01:9200

**Comment by kk0201** [comment]
Thanks for fixing it so quickly.
