### ISSUE TITLE
Dashboard Visualization Erros

### ISSUE THREAD

**Issue by sdresen** [pfelk/docker#20]
**Describe the bug**
Fresh install using Docker.  Visualizations in dashboards showing errors and not presenting data.

**To Reproduce**
1. Fresh install of Ubuntu 20.04
2. Fresh install of Docker
3. Fresh install of MaxMind
4. pfElk docker install script executed without errors
5. pfElk configuration followed in order without errors
![Index Mgmt](https://user-images.githubusercontent.com/33377441/102805109-be2a7980-4388-11eb-8313-3b9be2776882.png)
![Index Templates](https://user-images.githubusercontent.com/33377441/102805119-c1be0080-4388-11eb-8a66-20b493ab4a89.png)
![Saved Objects](https://user-images.githubusercontent.com/33377441/102805131-c5ea1e00-4388-11eb-97e9-91ed5107f2e9.png)
![Log Enrichment](https://user-images.githubusercontent.com/33377441/102805144-c97da500-4388-11eb-9d6c-4269018783cc.png)

**Screenshots**

**Operating System (please complete the following information):**
Linux 5.4.0-58-generic x86_64 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Docker version 20.10.1, build 831ebea
docker-compose version 1.25.0, build unknown

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK: ELK_VERSION=7.10.0
 
 **Service logs
[es01.log](https://github.com/pfelk/docker/files/5725616/es01.log)
[es02.log](https://github.com/pfelk/docker/files/5725619/es02.log)
[es03.log](https://github.com/pfelk/docker/files/5725620/es03.log)
[kibana.log](https://github.com/pfelk/docker/files/5725621/kibana.log)
[logstash.log](https://github.com/pfelk/docker/files/5725622/logstash.log)

**Additional context**
Screenshots
![DHCP_Dashboard](https://user-images.githubusercontent.com/33377441/102804695-19a83780-4388-11eb-9464-d1a80a609d2e.png)
![Firewall_Dashboard](https://user-images.githubusercontent.com/33377441/102804705-1ca32800-4388-11eb-8d29-8383805909ce.png)
![Unbound_Dashboard](https://user-images.githubusercontent.com/33377441/102804711-1e6ceb80-4388-11eb-86bf-b02fd7f6214a.png)

** Last Note of Interest**
I am using pfSense and yet the Observer.Name field shows "OPNSense" in the Discover view where you see the specific data enrichment fields (Log Enrichment screenshot).

**Comment by a3ilson** [comment]
@sdresen - Thanks for providing a detailed request.

Let's break this down into two segments:
1. `observer.name`
2. Dashboards not populating (i.e. errors)

## 1. Observer.Name
- This field is defined within the `02-types.conf` file along with `observer.product` and `observer.serial_number`
  - These fields are user defined
  - Amend to meet your needs (e.g. allow for delineation among multiple instances)
    - This is similar to the `07-interfaces.conf` where you can define your network interfaces and aliases (referenced [here](https://github.com/pfelk/pfelk/wiki/References:-Customized-Interface-Names)

## 2. Other errors
- Similar issues were noted with #223 and #224 on the main pfelk repo...Still trying to identify the culprit and the only commonality is pfSense (I'm running OPNsense).  
- Based on your provided screenshot, it appears that your logs are being parsed but the dashboards are reporting issues
  - Can you confirm the presence of `pfelk-settings` and `pfelk-mappings-ecs` templates are installed within Management>>Index Management>>Component Templates?
  - Try deleting all indices and after a few minutes see if that fixes the issue
  - Please provide a sample of the original.log messages (with and without the GROK failures)

**Comment by sdresen** [comment]
Thank you for the quick response.  I think deleting the indices did much of the trick to get the reporting working.  I updated the observer.product and observer.serial_number fields.  I did confirm that the pfelk-settings and pfelk-mappings-ecs are present in the Component Templates section (screen shot attached).

The Firewall and DHCP visualizations appear to be working correctly.  I'm still seeing "obj is undefined" for the Unbound dashboard.

Lastly, can you provide a bit more direction on the original.log message you'd like.  Not clear what I should send.

<img width="913" alt="Component Templates" src="https://user-images.githubusercontent.com/33377441/102811198-0058b880-4393-11eb-900c-d52e96259554.png">

**Comment by a3ilson** [comment]
@sdresen - Whew...glad that resolved most of the issue. I suspect that you had logs being sent prior to configuring (adding) the various templates if so the remedy is to purge the current indices which appears to have resolved your issue.

As for the unbound portion, are you running unbound (I assume you are)? However, the initial screenshot did not depict any indices (i.e. no received logs).

**Comment by sdresen** [comment]
The unbound issue may be that there's no DNS traffic hitting the pfSense unbound server.  Unbound is active and running but I use PiHole's internally.  So, could be simply that there's no traffic resolution hitting it.

**Comment by a3ilson** [comment]
That would be it! So looks like your up/running (e.g. everything good?).

**Comment by sdresen** [comment]
Yes, all good, many thanks!

**Comment by a3ilson** [comment]
Resolved
