### ISSUE TITLE
Installation Error Docker

### ISSUE THREAD

**Issue by ghost** [pfelk/docker#24]
(3b) Set vm.max_map_count to no less than 262144 (one time configuration)

sudo echo "vm.max_map_count=262144" >> /etc/sysctl.conf

Note this command failed with privileges on Debian Buster.
su root was required to run command

counciller@buster:~$ sudo echo "vm.max_map_count=262144" >> /etc/sysctl.conf
-bash: /etc/sysctl.conf: Permission denied
counciller@buster:~$ su root
Password: 
root@buster:/home/counciller# echo "vm.max_map_count=262144" >> /etc/sysctl.conf
root@buster:/home/counciller# exit

(4) Start Docker

sudo docker-compose up
Once fully running, navigate to the host ip (ex: 192.168.0.100:5601)

counciller@buster:~$ sudo docker-compose up
WARNING: The ELK_VERSION variable is not set. Defaulting to a blank string.
Creating network "counciller_elastic" with driver "bridge"
Creating volume "counciller_data01" with local driver
Creating volume "counciller_data02" with local driver
Creating volume "counciller_data03" with local driver
Building es01
Step 1/2 : ARG ELK_VERSION
Step 2/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
ERROR: Service 'es01' failed to build: invalid reference format

**Comment by a3ilson** [comment]
How much RAM does your system have?

**Comment by thepagan** [comment]
Same here, 24G ram. 6 cores. Ubuntu 20.04, with stock docker docker-compose.

`$ sudo docker-compose up`
`Building es01`
`Step 1/2 : ARG ELK_VERSION`
`Step 2/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}`
`ERROR: Service 'es01' failed to build: invalid reference format`

**Comment by a3ilson** [comment]
@thepagan - the initial issue was a result of insufficient ram.  I’ve tested and validated on an 8gb/1c VM. 

Please check the following:
- is the .env file present?
- How did you see the: vm.max_map_count=262144 ?
  - 3a or 3b?
  - 3a should work 
  - 3b may require a reboot and subsequent check to confirm it was/is set.

**Comment by thepagan** [comment]
Whelp that's the issue. The .env file is not present in the zip file. I manually created it and it seems to be working. Thanks!

**Comment by a3ilson** [comment]
Dang.... let me fix the zip file and apologize for the inconvenience.

**Comment by a3ilson** [comment]
Issue resolved with updated Zip file containing multiple fixes (Squid parsing and missing .env file)

**Comment by a3ilson** [comment]
Issue resolved with updated Zip file containing multiple fixes (Squid parsing and missing .env file)
