### ISSUE TITLE
Download Link in instructions still pointing to master instead of main

### ISSUE THREAD

**Issue by thowe-switzerland** [pfelk/docker#26]
**Describe the bug**
When one tries to follow the instructions, download e.g. of the docker ZIP file will fail because of changed branch name (master --> main).

**To Reproduce**
1. Go to 'https://github.com/pfelk/docker'
2. Follow instructions
3. At (2) Download pfELK Docker try to download the ZIP
4. See error 404 as master is now named main

**Comment by a3ilson** [comment]
@thowe-switzerland - Thanks for your input and apologies for the recent oversight. The issue was fixed/corrected.

**Comment by thowe-switzerland** [comment]
Thanks! Having a lot of fun with OPNsense and Pfelk. :-)

**Comment by a3ilson** [comment]
> Thanks! Having a lot of fun with OPNsense and Pfelk. :-)

Excellent! Hope it is useful and drop a line if you have any comments/suggestions.
