### ISSUE TITLE
logstash.yml still refers to http://es01:9200

### ISSUE THREAD

**Issue by panks21** [pfelk/docker#27]
https://github.com/pfelk/docker/blob/0a80883c771c9de15a92334cad94ba17cd4e6765/etc/logstash/config/logstash.yml#L11

Shouldn't it be 
```
xpack.monitoring.elasticsearch.hosts: [ "http://pfelk:9200" ]
```

**Comment by a3ilson** [comment]
The Elasticsearch hosts are es01, es02, and es03.  pfelk is not a defined host....additionally, these settings can be configured within the docker-compose.yml file, if desired.

Reference: https://www.elastic.co/guide/en/logstash/current/docker-config.html

**Comment by panks21** [comment]
Apologies for my ignorance 
In https://github.com/pfelk/docker/blob/main/scale/docker-compose.yml
I see the host defined as pfelk.. hence asked

**Comment by a3ilson** [comment]
@panks21 - no apologies needed. I didn't realize that you were referring to the scalable instance and you are correct if utilizing the scalable.

**Comment by panks21** [comment]
Thanks. Closing the issue
