### ISSUE TITLE
Disk space

### ISSUE THREAD

**Issue by dagobertdebug** [pfelk/docker#34]
Hi,

thanks for that great project!

I have a question regarding disk space: is there anything required to configure so that the disk of the pfelk host will not get full with logs? Is there a mechanisms that will free up some disk space after a certain amount is full?

Please head me into the right direction.

Thanks,
Dago

**Comment by a3ilson** [comment]
@dagobertdebug - you could configure/revise the ILM settings to delete logs based on time and/or size which would self manage your disk space.

**Comment by dagobertdebug** [comment]
@a3ilson, thanks for your reply and the hint!

I went to Stack Management ->Index Lifecycle Policies -> pfelk and changed the Warm Phase to 31 days, Cold Phase to 61 days and Delete Phase to 91 days.

Is it what you meant?

**Comment by a3ilson** [comment]
@dagobertdebug - that is correct! There is a trash can proceeded by "Keep data in this phase forever" under nested in the warm and cold phase that it selected will delete the data vs keep forever. 

I was incorrect/wrong in that you can define the phase by size. However that feature is being pursued ([issue #47764](https://github.com/elastic/elasticsearch/issues/47764)).
