### ISSUE TITLE
config of 50-output

### ISSUE THREAD

**Issue by xchg-ax-ax** [pfelk/docker#9]
**Describe the bug**
A reference to pfelk01 still exists in logstash config file 50-outputs.conf. This prevents logstash from finding the elasticsearch instance, when running with a single elasticsearch instance.

**Comment by a3ilson** [comment]
@xchg-ax-ax - Updated 50-outputs.conf.  Thanks and please give it another try.

**Comment by xchg-ax-ax** [comment]
This works! thx!
